require 'game/object_extensions/ability'
require 'game/object_extensions/character'
require 'game/object_extensions/corporeal'
require 'game/object_extensions/mob'
require 'game/object_extensions/npc'
require 'game/object_extensions/shared'
